config/routes.rb
Rails.application.routes.draw do
  resources :dragonfly_images

  resources :carrierwave_images

  resources :paperclip_images

  root 'high_voltage/pages#show', id: 'home'

end

app/models/carrierwave_image.rb
class CarrierwaveImage < ActiveRecord::Base
  mount_uploader :asset, AssetUploader
end

app/models/dragonfly_image.rb
class DragonflyImage < ActiveRecord::Base
  dragonfly_accessor :asset
end

app/models/paperclip_image.rb
class PaperclipImage < ActiveRecord::Base
  has_attached_file :asset, styles: {
    medium: '300x300>',
    small: '140x140>',
    thumb: '64x64!'
  }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carrierwave_images_controller.rb
class CarrierwaveImagesController < ApplicationController
  before_action :set_carrierwave_image, only: [:show, :edit, :update, :destroy]

  # GET /carrierwave_images
  # GET /carrierwave_images.json
  def index
    @carrierwave_images = CarrierwaveImage.all
  end

  # GET /carrierwave_images/1
  # GET /carrierwave_images/1.json
  def show
  end

  # GET /carrierwave_images/new
  def new
    @carrierwave_image = CarrierwaveImage.new
  end

  # GET /carrierwave_images/1/edit
  def edit
  end

  # POST /carrierwave_images
  # POST /carrierwave_images.json
  def create
    @carrierwave_image = CarrierwaveImage.new(carrierwave_image_params)

    respond_to do |format|
      if @carrierwave_image.save
        format.html { redirect_to @carrierwave_image, notice: 'Carrierwave image was successfully created.' }
        format.json { render :show, status: :created, location: @carrierwave_image }
      else
        format.html { render :new }
        format.json { render json: @carrierwave_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carrierwave_images/1
  # PATCH/PUT /carrierwave_images/1.json
  def update
    respond_to do |format|
      if @carrierwave_image.update(carrierwave_image_params)
        format.html { redirect_to @carrierwave_image, notice: 'Carrierwave image was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrierwave_image }
      else
        format.html { render :edit }
        format.json { render json: @carrierwave_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carrierwave_images/1
  # DELETE /carrierwave_images/1.json
  def destroy
    @carrierwave_image.destroy
    respond_to do |format|
      format.html { redirect_to carrierwave_images_url, notice: 'Carrierwave image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrierwave_image
      @carrierwave_image = CarrierwaveImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrierwave_image_params
      params.require(:carrierwave_image).permit(:asset, :remove_asset)
    end
end

app/controllers/dragonfly_images_controller.rb
class DragonflyImagesController < ApplicationController
  before_action :set_dragonfly_image, only: [:show, :edit, :update, :destroy]

  # GET /dragonfly_images
  # GET /dragonfly_images.json
  def index
    @dragonfly_images = DragonflyImage.all
  end

  # GET /dragonfly_images/1
  # GET /dragonfly_images/1.json
  def show
  end

  # GET /dragonfly_images/new
  def new
    @dragonfly_image = DragonflyImage.new
  end

  # GET /dragonfly_images/1/edit
  def edit
  end

  # POST /dragonfly_images
  # POST /dragonfly_images.json
  def create
    @dragonfly_image = DragonflyImage.new(dragonfly_image_params)

    respond_to do |format|
      if @dragonfly_image.save
        format.html { redirect_to @dragonfly_image, notice: 'Dragonfly image was successfully created.' }
        format.json { render :show, status: :created, location: @dragonfly_image }
      else
        format.html { render :new }
        format.json { render json: @dragonfly_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dragonfly_images/1
  # PATCH/PUT /dragonfly_images/1.json
  def update
    respond_to do |format|
      if @dragonfly_image.update(dragonfly_image_params)
        format.html { redirect_to @dragonfly_image, notice: 'Dragonfly image was successfully updated.' }
        format.json { render :show, status: :ok, location: @dragonfly_image }
      else
        format.html { render :edit }
        format.json { render json: @dragonfly_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dragonfly_images/1
  # DELETE /dragonfly_images/1.json
  def destroy
    @dragonfly_image.destroy
    respond_to do |format|
      format.html { redirect_to dragonfly_images_url, notice: 'Dragonfly image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dragonfly_image
      @dragonfly_image = DragonflyImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dragonfly_image_params
      params.require(:dragonfly_image).permit(:asset)
    end
end

app/controllers/paperclip_images_controller.rb
class PaperclipImagesController < ApplicationController
  before_action :set_paperclip_image, only: [:show, :edit, :update, :destroy]

  # GET /paperclip_images
  # GET /paperclip_images.json
  def index
    @paperclip_images = PaperclipImage.all
  end

  # GET /paperclip_images/1
  # GET /paperclip_images/1.json
  def show
  end

  # GET /paperclip_images/new
  def new
    @paperclip_image = PaperclipImage.new
  end

  # GET /paperclip_images/1/edit
  def edit
  end

  # POST /paperclip_images
  # POST /paperclip_images.json
  def create
    @paperclip_image = PaperclipImage.new(paperclip_image_params)

    respond_to do |format|
      if @paperclip_image.save
        format.html { redirect_to @paperclip_image, notice: 'Paperclip image was successfully created.' }
        format.json { render :show, status: :created, location: @paperclip_image }
      else
        format.html { render :new }
        format.json { render json: @paperclip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paperclip_images/1
  # PATCH/PUT /paperclip_images/1.json
  def update
    respond_to do |format|
      if @paperclip_image.update(paperclip_image_params)
        format.html { redirect_to @paperclip_image, notice: 'Paperclip image was successfully updated.' }
        format.json { render :show, status: :ok, location: @paperclip_image }
      else
        format.html { render :edit }
        format.json { render json: @paperclip_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paperclip_images/1
  # DELETE /paperclip_images/1.json
  def destroy
    @paperclip_image.destroy
    respond_to do |format|
      format.html { redirect_to paperclip_images_url, notice: 'Paperclip image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paperclip_image
      @paperclip_image = PaperclipImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paperclip_image_params
      params.require(:paperclip_image).permit(:asset)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carrierwave_images_helper.rb
module CarrierwaveImagesHelper
end

app/helpers/dragonfly_images_helper.rb
module DragonflyImagesHelper
end

app/helpers/paperclip_images_helper.rb
module PaperclipImagesHelper
end

app/views/carrierwave_images/_form.html.erb
<%= form_for(@carrierwave_image) do |f| %>
  <% if @carrierwave_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrierwave_image.errors.count, "error") %> prohibited this carrierwave_image from being saved:</h2>

      <ul>
      <% @carrierwave_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :asset %>
    <%= f.file_field :asset %>
    <% if f.object.asset? %>
      <p>
      <%= image_tag f.object.asset.small.url %>

      <em>Current image</em>
      </p>
      <br />
      <%= f.label :remove_asset %>
      <%= f.check_box :remove_asset %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/carrierwave_images/edit.html.erb
<h1>Editing carrierwave_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrierwave_image %> |
<%= link_to 'Back', carrierwave_images_path %>

app/views/carrierwave_images/index.html.erb
<h1>Listing carrierwave_images</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrierwave_images.each do |carrierwave_image| %>
      <tr>
        <td><%= link_to image_tag(carrierwave_image.asset.thumb.url), carrierwave_image %></td>
        <td><%= link_to 'Edit', edit_carrierwave_image_path(carrierwave_image) %></td>
        <td><%= link_to 'Destroy', carrierwave_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrierwave image', new_carrierwave_image_path %>

app/views/carrierwave_images/new.html.erb
<h1>New carrierwave_image</h1>

<%= render 'form' %>

<%= link_to 'Back', carrierwave_images_path %>

app/views/carrierwave_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @carrierwave_image.asset.medium.url, class: "img-thumbnail" %>

<%= link_to 'Edit', edit_carrierwave_image_path(@carrierwave_image) %> |
<%= link_to 'Back', carrierwave_images_path %>

app/views/dragonfly_images/_form.html.erb
<%= form_for(@dragonfly_image) do |f| %>
  <% if @dragonfly_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dragonfly_image.errors.count, "error") %> prohibited this dragonfly_image from being saved:</h2>

      <ul>
      <% @dragonfly_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :asset %>
    <%= f.file_field :asset %>
    <% if f.object.asset_stored? %>
      <%= image_tag f.object.asset.thumb('140x140').url, class: 'img-thumbnail' %>
      <em>Current image</em>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/dragonfly_images/edit.html.erb
<h1>Editing dragonfly_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @dragonfly_image %> |
<%= link_to 'Back', dragonfly_images_path %>

app/views/dragonfly_images/index.html.erb
<h1>Listing dragonfly_images</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dragonfly_images.each do |dragonfly_image| %>
      <tr>
        <td><%= link_to image_tag(dragonfly_image.asset.thumb('64x64!').url, class: "img-thumbnail"), dragonfly_image %></td>
        <td><%= link_to 'Edit', edit_dragonfly_image_path(dragonfly_image) %></td>
        <td><%= link_to 'Destroy', dragonfly_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dragonfly image', new_dragonfly_image_path %>

app/views/dragonfly_images/new.html.erb
<h1>New dragonfly_image</h1>

<%= render 'form' %>

<%= link_to 'Back', dragonfly_images_path %>

app/views/dragonfly_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @dragonfly_image.asset.thumb('300x300').url, class: "img-thumbnail" if @dragonfly_image.asset_stored? %>

<%= link_to 'Edit', edit_dragonfly_image_path(@dragonfly_image) %> |
<%= link_to 'Back', dragonfly_images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'bootstrap.min.css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Image Uploading Example</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><%= link_to "Paperclip", paperclip_images_path %></li>
          <li><%= link_to "CarrierWave", carrierwave_images_path %></li>
          <li><%= link_to "Dragonfly", dragonfly_images_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container">
   <%= yield %>
  </div>

  <%= javascript_include_tag "bootstrap.min" %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Rails 4 Image Uploading Example App</h1>

<p>A Treehouse livestream example application using the following projects:</p>

<ul>
  <li><a href="https://github.com/thoughtbot/paperclip">Paperclip</a></li>
  <li><a href="https://github.com/carrierwaveuploader/carrierwave">Carrierwave</a></li>
  <li><a href="http://markevans.github.io/dragonfly/">Dragonfly</a></li>
</ul>

app/views/paperclip_images/_form.html.erb
<%= form_for @paperclip_image, html: { multipart: true } do |f| %>
  <% if @paperclip_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paperclip_image.errors.count, "error") %> prohibited this paperclip_image from being saved:</h2>

      <ul>
      <% @paperclip_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :asset %>
    <%= f.file_field :asset, html: { class: 'form-control' } %>
    <% if f.object.asset? %>
        <br />
        <%= image_tag(f.object.asset.url(:small)) %><br />
        <em>Currently uploaded image</em>
        <p>
        <%= f.object.asset_file_name %>
        </p>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/paperclip_images/edit.html.erb
<h1>Editing paperclip_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @paperclip_image %> |
<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/index.html.erb
<h1>Listing paperclip_images</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paperclip_images.each do |paperclip_image| %>
      <tr>
        <td><%= link_to image_tag(paperclip_image.asset.url(:thumb), class: "img-thumbnail"), paperclip_image %></td>
        <td><%= link_to 'Edit', edit_paperclip_image_path(paperclip_image) %></td>
        <td><%= link_to 'Destroy', paperclip_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paperclip image', new_paperclip_image_path %>

app/views/paperclip_images/new.html.erb
<h1>New paperclip_image</h1>

<%= render 'form' %>

<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @paperclip_image.asset.url(:medium), class: "img-thumbnail" %>

<%= link_to 'Edit', edit_paperclip_image_path(@paperclip_image) %> |
<%= link_to 'Back', paperclip_images_path %>